In [1]:
import pandas as pd
import numpy as np

In [6]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[1,2,3,4]])
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [8]:
a = np.arange(1,99,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

interpolation lineaire

In [11]:
b = np.linspace(3,5,4)
b # va prendre des valerus entre 2 bornes et combien de valeurs entre les 2 
# et va calculer les valeurs pour uqe ça rentre entre les bornes

array([3.        , 3.66666667, 4.33333333, 5.        ])

In [13]:
b = np.linspace(3,5,4,dtype=int)
b

array([3, 3, 4, 5])

In [76]:
rng = np.random.default_rng()
b = np.random.randint(-5,5)
b

rng.integers(0,10) # endpoint, F exclure T inclure borne max



np.int64(0)

In [79]:
a = np.ndarray.flatten(a) # vrai copie 
a

np.vstack() # ajout lignes
np.hstack() # ajout colonnes

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [227]:
# chaque colonne de df est une pd.series
url = "https://www.data.gouv.fr/api/1/datasets/r/f5df602b-3800-44d7-b2df-fa40a0350325"

path = 'communes-france-2025.csv'
# df=pd.read_csv(url)
df = pd.read_csv(path,index_col=0 , dtype={'population':int})



/tmp/ipykernel_12624/19813951.py:6: DtypeWarning: Columns (1,12,14,16,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path,index_col=0 , dtype={'population':int})


In [228]:
df.columns


Index(['code_insee', 'nom_standard', 'nom_sans_pronom', 'nom_a', 'nom_de',
       'nom_sans_accent', 'nom_standard_majuscule', 'typecom', 'typecom_texte',
       'reg_code', 'reg_nom', 'dep_code', 'dep_nom', 'canton_code',
       'canton_nom', 'epci_code', 'epci_nom', 'academie_code', 'academie_nom',
       'code_postal', 'codes_postaux', 'zone_emploi',
       'code_insee_centre_zone_emploi', 'code_unite_urbaine',
       'nom_unite_urbaine', 'taille_unite_urbaine',
       'type_commune_unite_urbaine', 'statut_commune_unite_urbaine',
       'population', 'superficie_hectare', 'superficie_km2', 'densite',
       'altitude_moyenne', 'altitude_minimale', 'altitude_maximale',
       'latitude_mairie', 'longitude_mairie', 'latitude_centre',
       'longitude_centre', 'grille_densite', 'grille_densite_texte',
       'niveau_equipements_services', 'niveau_equipements_services_texte',
       'gentile', 'url_wikipedia', 'url_villedereve'],
      dtype='object')

In [ ]:
# print(df.groupby('dep_code'))

grouped_df = df.groupby('dep_code')

# for key, item in grouped_df:
#     print(grouped_df.get_group(key), "\n\n")


cols = set(df.columns)

needed_cols = ['code_insee'
,'nom_sans_accent'
,'reg_nom'
,'dep_code'
,'academie_nom'
,'type_commune_unite_urbaine'
,'population'
,'superficie_hectare'
,'altitude_moyenne'
,'latitude_centre'
,'longitude_centre'
,'niveau_equipements_services']


# print(needed_cols.issubset(cols))


# i = 0
# for el in needed_cols:
#     if el not in cols:
#         print(el)


# if 'population' in cols:
#     print('True')


df_2 = df[['code_insee','nom_sans_accent','reg_nom','dep_code','academie_nom','type_commune_unite_urbaine','population','superficie_hectare','altitude_moyenne','latitude_centre','longitude_centre','niveau_equipements_services']]

df_2 = df.loc[:,['code_insee','nom_sans_accent','reg_nom','dep_code','academie_nom','type_commune_unite_urbaine','population','superficie_hectare','altitude_moyenne','latitude_centre','longitude_centre','niveau_equipements_services']]


df_2.head()


print(df.population.astype(int).sum())


# print(df[df.loc[:,'nom_sans_accent']=='moissac'])


# print(df.loc[(df.population.astype(int)>100000)])

df_100k = df[df.population.astype(int)>100000]


df[df.population.astype(int)>10000].groupby(['reg_nom']).size().sort_values(ascending=False).head(3)

barycentre_l = df.lati  .sort_values()
print(barycentre_l[len(barycentre_l)//2])


# print(df.columns)
# barycentre_l = df.lo.sort_values()
# print(barycentre_l[len(barycentre_l)//2])

67648309


AttributeError: 'DataFrame' object has no attribute 'latitude_minimale'